// 實際 FYP 項目數據 - 來自 ELEC S411F Supervisor Project List (CCS) 2025/2026
const fypProjectsData = [
  // Alex 的 Cybersecurity 項目
  {
    id: 11,
    code: "D11",
    title: "Cybersecurity Dashboard for Small Businesses",
    supervisor: "Alex",
    supervisorId: "T001",
    description: "This project involves creating an intuitive and user-friendly cybersecurity dashboard tailored for small businesses to monitor and improve their cybersecurity posture. Small businesses often lack the resources and expertise to manage complex cybersecurity tools, leaving them vulnerable to attacks. The proposed dashboard will provide an all-in-one solution with features such as vulnerability scanning to identify weaknesses in systems and networks, password management to enforce strong authentication practices, and real-time threat alerts to notify users of potential risks. The dashboard will also include visual analytics, such as graphs and heatmaps, to help users understand their security status at a glance. Additionally, it will offer actionable recommendations to address identified vulnerabilities and improve overall security. The project will focus on accessibility, ensuring the tool is easy to use for non-technical users, while providing robust protection against common cyber threats.",
    skills: ["Python", "JavaScript", "Web Development", "Cybersecurity"],
    capacity: 3,
    status: "active",
    createdAt: "2025-01-15",
    department: "Computer Science",
    category: "Cybersecurity"
  },
  {
    id: 12,
    code: "D12",
    title: "Social Engineering Awareness Tool",
    supervisor: "Alex",
    supervisorId: "T001",
    description: "This project focuses on building an interactive tool designed to educate users about social engineering attacks, such as phishing, baiting, pretexting, and tailgating. Social engineering exploits human vulnerabilities rather than technical flaws, making awareness and education critical in cybersecurity. The tool will simulate real-world scenarios, allowing users to experience and identify common tactics used by attackers. For example, users may interact with simulated phishing emails, malicious websites, or baiting attempts, learning to recognize red flags and avoid falling victim. The tool will include quizzes, gamified learning modules, and detailed explanations of each attack type, along with actionable tips for prevention. Additionally, the project will emphasize user engagement by incorporating visual aids, interactive elements, and real-time feedback. By raising awareness and improving user vigilance, this tool aims to reduce the success rate of social engineering attacks and strengthen the human element of cybersecurity.",
    skills: ["Python", "JavaScript", "UI/UX Design"],
    capacity: 2,
    status: "active",
    createdAt: "2025-01-15",
    department: "Computer Science",
    category: "Cybersecurity"
  },
  {
    id: 13,
    code: "D13",
    title: "Blockchain-Based Voting System",
    supervisor: "Alex",
    supervisorId: "T001",
    description: "This project aims to design and implement a blockchain-based voting system to ensure secure, transparent, and tamper-proof elections. The system will leverage blockchain technology to store votes in an immutable ledger, preventing tampering and ensuring the integrity of election results. Each vote will be cryptographically secured and linked to the blockchain, guaranteeing transparency while maintaining voter anonymity. The project will explore the use of smart contracts to automate vote validation, tallying, and result publication. Additionally, the system will incorporate mechanisms to prevent double voting, ensure voter authentication, and provide audit trails for election authorities. The research will address challenges such as scalability, privacy, and accessibility to make the system practical for large-scale elections. By combining cybersecurity principles with blockchain technology, this project contributes to the development of a secure and trustworthy voting system that can be used in democratic processes worldwide.",
    skills: ["Python", "JavaScript", "Blockchain", "Cryptography"],
    capacity: 2,
    status: "active",
    createdAt: "2025-01-15",
    department: "Computer Science",
    category: "Cybersecurity"
  },
  {
    id: 14,
    code: "D14",
    title: "Mobile Application Security Testing Tool",
    supervisor: "Alex",
    supervisorId: "T001",
    description: "Build a tool to test the security of mobile applications. The tool should identify vulnerabilities like insecure data storage, weak encryption, and improper API usage. This project involves designing and developing a comprehensive tool to test the security of mobile applications. The tool will focus on identifying common vulnerabilities such as insecure data storage, weak encryption, improper API usage, and insecure communication protocols. It will automate the process of scanning mobile apps for security flaws, providing developers and security professionals with actionable insights to improve app security. The tool will include features such as static code analysis, dynamic runtime testing, and API endpoint validation. It will also provide detailed reports highlighting vulnerabilities, their severity, and recommendations for mitigation. The project will emphasize user-friendliness, enabling developers with limited cybersecurity expertise to easily test their apps. Additionally, the tool can include support for both Android and iOS platforms, making it versatile for modern mobile app development. This project contributes to improving mobile app security and protecting user data from potential threats.",
    skills: ["Python", "Java", "Mobile Development", "Security Testing"],
    capacity: 2,
    status: "active",
    createdAt: "2025-01-15",
    department: "Computer Science",
    category: "Cybersecurity"
  },

  // Bell 的項目
  {
    id: 21,
    code: "L11",
    title: "Smart Book Sharing Platform",
    supervisor: "Bell",
    supervisorId: "T002",
    description: "This project requires student to design an android app to build a book sharing platform. Here are the details of the platform. - show all available books - borrow books - donate books",
    skills: ["Android Studio", "Java", "Google Books API"],
    capacity: 2,
    status: "active",
    createdAt: "2025-01-15",
    department: "Computer Science",
    category: "Mobile Development"
  },
  {
    id: 22,
    code: "L12",
    title: "FYP Matching System for Students and Teachers",
    supervisor: "Bell",
    supervisorId: "T002",
    description: "This project requires student to build an automatic fyp matching system for students and teachers. The system should support different types of users such as teachers, students, and admin. The system may includes three stages: 1. student self-proposing projects; 2. teacher proposing projects; 3. final matching result.",
    skills: ["MERN Stack", "Web Development"],
    capacity: 3,
    status: "active",
    createdAt: "2025-01-15",
    department: "Computer Science",
    category: "Web Development"
  },
  {
    id: 23,
    code: "L13",
    title: "An Interactive Series-Game for Mastering Cisco Packet Tracer Commands",
    supervisor: "Bell",
    supervisorId: "T002",
    description: "This project is to help course ELEC S315F Routing and Switching Technologies to design a series of games based on Cisco Pakcet Tracer. All students of ELEC S315 are allowed to play the games together in the multi-user mode in packet tracer. These games are used for students to be familiar with Cisco Packet Tracer command.",
    skills: ["Cisco Packet Tracer"],
    capacity: 2,
    status: "active",
    createdAt: "2025-01-15",
    department: "Computer Science",
    category: "Networking"
  },
  {
    id: 24,
    code: "L14",
    title: "Advanced Network Scanner Using Nmap",
    supervisor: "Bell",
    supervisorId: "T002",
    description: "The advanced network scanner will utilize the Nmap scripting engine. The scanner will utilize custom or pre-existing Nmap scripts to automate complex tasks and gather detailed information about networked devices and services. It will support various scanning techniques, including host discovery, port scanning, service enumeration, and vulnerability detection.",
    skills: ["Wireshark", "Nmap", "Network Security"],
    capacity: 2,
    status: "active",
    createdAt: "2025-01-15",
    department: "Computer Science",
    category: "Networking"
  },
  {
    id: 25,
    code: "L15",
    title: "Cybersecurity Awareness APP",
    supervisor: "Bell",
    supervisorId: "T002",
    description: "The cybersecurity awareness app can help users stay safe from identity theft, phishing, cyberbullying, and privacy violations. It is an engaging platform for cybersecurity awareness training that instructs users on safe behaviors, different risks, and how to spot and handle phishing efforts. The aim is to assist in defending school officials, instructors, and students against data breaches and cyberattacks. Lessen the impact of cyberattacks and teach teachers and students how to recognize and react to threats.",
    skills: ["MERN Stack", "Android Studio", "Java"],
    capacity: 3,
    status: "active",
    createdAt: "2025-01-15",
    department: "Computer Science",
    category: "Cybersecurity"
  },

  // Adam 的工業控制和網路安全項目
  {
    id: 31,
    code: "A11",
    title: "Cyberattack Impact on Smart Grid Control",
    supervisor: "Adam",
    supervisorId: "T003",
    description: "Simulate a simplified smart power grid control system (frequency control or dispatch control) and investigate how cyberattacks (such as false data or delayed signals) can cause incorrect operational decisions. This project reflects real-world Smart Grid cybersecurity challenges faced by power companies and energy providers, a growing field in critical infrastructure protection. Completing it gives you skills directly applicable to roles in energy systems engineering, critical infrastructure security, and control system analysis.",
    skills: ["Python", "Matlab", "Control Systems"],
    capacity: 2,
    status: "active",
    createdAt: "2025-01-15",
    department: "Electronic Engineering",
    category: "Cybersecurity"
  },
  {
    id: 32,
    code: "A12",
    title: "Cybersecurity Monitoring for a Smart Factory Digital Twin",
    supervisor: "Adam",
    supervisorId: "T003",
    description: "Build a simple digital twin simulation of a smart manufacturing process (e.g., conveyor belt or packaging line) and apply an open-source Intrusion Detection System (IDS) to detect abnormal network commands caused by cyberattacks. This mirrors how Industry 4.0 factories secure their automated systems against hackers. Experience with this project is valued in manufacturing automation, industrial IoT security, and operational technology (OT) engineering roles.",
    skills: ["Python", "Matlab", "Snort"],
    capacity: 2,
    status: "active",
    createdAt: "2025-01-15",
    department: "Electronic Engineering",
    category: "Cybersecurity"
  },
  {
    id: 33,
    code: "A13",
    title: "Anomaly Detection in Industrial Control System Data",
    supervisor: "Adam",
    supervisorId: "T003",
    description: "Create a simple Python program that simulates industrial control system data (temperature, motor speed, etc.), inject anomalies (attacks or faults), and use basic machine learning to detect these irregular patterns. This matches how industries use predictive maintenance and industrial cybersecurity to keep production safe, making it valuable for jobs in data analytics, industrial automation, and ML-assisted monitoring.",
    skills: ["Python", "Matlab", "Machine Learning"],
    capacity: 2,
    status: "active",
    createdAt: "2025-01-15",
    department: "Electronic Engineering",
    category: "Industrial Control"
  },
  {
    id: 34,
    code: "A14",
    title: "Security Evaluation of AI-Powered Industrial Chatbots",
    supervisor: "Adam",
    supervisorId: "T003",
    description: "Develop a Python-based LLM chatbot assistant for industrial operations (smart factory troubleshooting or smart grid helpdesk) and test how it can be tricked into giving unsafe or confidential answers (prompt injection, data leakage). Then implement a basic safeguard to block malicious queries. This project links to the fast-growing field of AI safety and industrial AI applications, valued by employers working on AI integration and secure automation.",
    skills: ["Python", "AI/ML", "Security Testing"],
    capacity: 2,
    status: "active",
    createdAt: "2025-01-15",
    department: "Electronic Engineering",
    category: "AI Security"
  },
  {
    id: 35,
    code: "A15",
    title: "Cybersecurity Risk Demonstration for a Smart Healthcare Monitoring System",
    supervisor: "Adam",
    supervisorId: "T003",
    description: "Simulate a basic smart healthcare IoT monitoring system (e.g., wearable heart rate monitor sending patient data to a hospital server) and study how cyberattacks, such as data tampering or eavesdropping, could compromise patient safety. Implement a simple security enhancement (like data validation or lightweight encryption) and evaluate its effectiveness. This project reflects real risks in connected medical device security, which is a fast-growing area in healthcare IT, IoT security, and medical data protection. Employers in health tech, embedded systems, and cybersecurity value this knowledge.",
    skills: ["Python", "IoT", "Healthcare"],
    capacity: 2,
    status: "active",
    createdAt: "2025-01-15",
    department: "Electronic Engineering",
    category: "Healthcare Security"
  },

  // Yaru 的 AI 和控制項目
  {
    id: 41,
    code: "Y11",
    title: "Deep Reinforcement Learning-Based Intelligent Traffic Light Control System",
    supervisor: "Yaru",
    supervisorId: "T004",
    description: "Deep Reinforcement Learning (DRL) technology revolutionizes traffic scenarios by offering intelligent solutions for optimizing traffic flow, reducing congestion, and enhancing safety on the roads. DRL algorithms can dynamically adjust traffic signals based on real-time conditions, improving traffic efficiency and reducing emissions. In this context, corresponding traffic light control plays a pivotal role, enabling adaptive signal timings that respond to changing traffic patterns and prioritize movements to minimize delays. Efficient traffic light control algorithms based on DRL facilitate multi-agent coordination, ensuring synchronized movements at intersections and continuous learning from traffic data for ongoing improvement in traffic management strategies. In this project, the student is expected to learn the principles of the Markov Decision Process (MDP) and DRL and apply them to the traffic light control system based on currencies. Both synthetic datasets and real datasets are expected to be used in simulations.",
    skills: ["TensorFlow", "PyTorch", "Reinforcement Learning"],
    capacity: 2,
    status: "active",
    createdAt: "2025-01-15",
    department: "Computer Science",
    category: "AI/ML"
  },
  {
    id: 42,
    code: "Y12",
    title: "Reinforcement Learning-Based Intelligent Light Adjustment Design",
    supervisor: "Yaru",
    supervisorId: "T004",
    description: "With the development of smart home technology, traditional lighting control methods (such as manual switching and fixed brightness) have become difficult to meet the demands of 'on-demand lighting' and 'energy conservation and consumption reduction'. This project aims to design and implement an intelligent lighting adjustment system based on Reinforcement Learning (RL). By simulating or perceiving environmental states (such as light intensity, human presence, and time periods), the system can independently learn the optimal brightness adjustment strategy. Minimize energy consumption while ensuring the user's lighting comfort.",
    skills: ["Python", "PyTorch", "Reinforcement Learning"],
    capacity: 2,
    status: "active",
    createdAt: "2025-01-15",
    department: "Computer Science",
    category: "Smart Home"
  }
];

module.exports = fypProjectsData;
