// 模擬數據庫
// 注意：這個文件作為 fallback，當 MongoDB 未連接時使用
//
// 30 個教師項目：15 CCS + 15 ECE；8 位導師（t001–t008）：Bell, Alex, Farah, Adam, Hugh, Steven, Tabitha, Yaru
// 每位導師負責項目數見 services/projectCatalogSync.js（種子會同步 supervisor / skills 到 MongoDB）

const mockData = {
    projects: [
        // ── CCS Projects (projects 1-15, major = CCS) ──────────────────────────
        {
            id: 1,
            title: "AI-based Learning System",
            supervisor: "Prof. Bell Liu",
            supervisorId: "T001",
            supervisorEmail: "t001@hkmu.edu.hk",
            description: "Develop an intelligent learning platform that adapts to student learning patterns using machine learning algorithms.",
            skills: ["Python", "Machine Learning", "Web Development"],
            popularity: 15,
            capacity: 3,
            status: "active",
            type: "teacher",
            category: "AI/ML",
            major: "CCS",
            createdAt: "2025-01-15"
        },
        {
            id: 2,
            title: "Cybersecurity Awareness Training Platform",
            supervisor: "Prof. David Reyes",
            supervisorId: "T003",
            supervisorEmail: "t003@hkmu.edu.hk",
            description: "Build an interactive web-based platform to train employees on cybersecurity threats, phishing awareness, and best practices.",
            skills: ["Web Development", "Cybersecurity", "JavaScript"],
            popularity: 9,
            capacity: 2,
            status: "active",
            type: "teacher",
            category: "Security",
            major: "CCS",
            createdAt: "2025-01-10"
        },
        {
            id: 3,
            title: "Machine Learning for Malware Detection",
            supervisor: "Prof. Alex Foster",
            supervisorId: "T002",
            supervisorEmail: "t002@hkmu.edu.hk",
            description: "Train and evaluate ML models to detect and classify malware executables based on static and dynamic features.",
            skills: ["Python", "Machine Learning", "Cybersecurity"],
            popularity: 12,
            capacity: 2,
            status: "active",
            type: "teacher",
            category: "Security",
            major: "CCS",
            createdAt: "2025-01-12"
        },
        {
            id: 4,
            title: "Secure Mobile Banking Application",
            supervisor: "Prof. Farah Patel",
            supervisorId: "T004",
            supervisorEmail: "t004@hkmu.edu.hk",
            description: "Design and implement a secure mobile banking app with biometric authentication, end-to-end encryption, and fraud detection.",
            skills: ["Mobile Development", "Cybersecurity", "Java"],
            popularity: 11,
            capacity: 3,
            status: "active",
            type: "teacher",
            category: "Mobile App",
            major: "CCS",
            createdAt: "2025-01-08"
        },
        {
            id: 5,
            title: "Cloud Security Compliance Checker",
            supervisor: "Prof. Priya Sharma",
            supervisorId: "T006",
            supervisorEmail: "t006@hkmu.edu.hk",
            description: "Develop a tool that audits cloud infrastructure against security frameworks such as ISO 27001 and NIST, generating compliance reports.",
            skills: ["Cloud Computing", "Cybersecurity", "Python"],
            popularity: 7,
            capacity: 2,
            status: "active",
            type: "teacher",
            category: "Cloud",
            major: "CCS",
            createdAt: "2025-01-05"
        },
        {
            id: 6,
            title: "Network Intrusion Detection System",
            supervisor: "Prof. Noah Kim",
            supervisorId: "T005",
            supervisorEmail: "t005@hkmu.edu.hk",
            description: "Build a real-time network intrusion detection system using signature-based and anomaly-based detection techniques.",
            skills: ["Python", "Cybersecurity", "IoT"],
            popularity: 10,
            capacity: 2,
            status: "active",
            type: "teacher",
            category: "Security",
            major: "CCS",
            createdAt: "2025-01-18"
        },
        {
            id: 7,
            title: "AI-powered Sentiment Analysis for Social Media",
            supervisor: "Prof. Bell Liu",
            supervisorId: "T001",
            supervisorEmail: "t001@hkmu.edu.hk",
            description: "Build an NLP pipeline to analyze sentiment on social media posts, with visualization dashboards and real-time alerts.",
            skills: ["Python", "Machine Learning", "Data Science"],
            popularity: 13,
            capacity: 3,
            status: "active",
            type: "teacher",
            category: "AI/ML",
            major: "CCS",
            createdAt: "2025-01-20"
        },
        {
            id: 8,
            title: "E-commerce Recommendation Engine",
            supervisor: "Prof. Alex Foster",
            supervisorId: "T002",
            supervisorEmail: "t002@hkmu.edu.hk",
            description: "Design a collaborative-filtering and content-based recommendation engine for e-commerce, with A/B testing support.",
            skills: ["Python", "Machine Learning", "Web Development"],
            popularity: 8,
            capacity: 2,
            status: "active",
            type: "teacher",
            category: "AI/ML",
            major: "CCS",
            createdAt: "2025-01-22"
        },
        {
            id: 9,
            title: "Blockchain-based Supply Chain Tracking System",
            supervisor: "Prof. David Reyes",
            supervisorId: "T003",
            supervisorEmail: "t003@hkmu.edu.hk",
            description: "Implement a permissioned blockchain solution to provide end-to-end transparency and traceability in supply chain logistics.",
            skills: ["Blockchain", "Python", "Web Development"],
            popularity: 6,
            capacity: 2,
            status: "active",
            type: "teacher",
            category: "Blockchain",
            major: "CCS",
            createdAt: "2025-01-25"
        },
        {
            id: 10,
            title: "Digital Forensics Investigation Toolkit",
            supervisor: "Prof. Farah Patel",
            supervisorId: "T004",
            supervisorEmail: "t004@hkmu.edu.hk",
            description: "Create an integrated toolkit for digital forensics, covering disk imaging, log analysis, and evidence chain-of-custody documentation.",
            skills: ["Cybersecurity", "Python", "C/C++"],
            popularity: 7,
            capacity: 2,
            status: "active",
            type: "teacher",
            category: "Security",
            major: "CCS",
            createdAt: "2025-01-28"
        },
        {
            id: 11,
            title: "Automated Penetration Testing Framework",
            supervisor: "Prof. Noah Kim",
            supervisorId: "T005",
            supervisorEmail: "t005@hkmu.edu.hk",
            description: "Develop an automated framework that performs network scanning, vulnerability assessment, and exploit simulation.",
            skills: ["Cybersecurity", "Python", "IoT"],
            popularity: 9,
            capacity: 2,
            status: "active",
            type: "teacher",
            category: "Security",
            major: "CCS",
            createdAt: "2025-02-01"
        },
        {
            id: 12,
            title: "Zero-Trust Architecture Implementation",
            supervisor: "Prof. Priya Sharma",
            supervisorId: "T006",
            supervisorEmail: "t006@hkmu.edu.hk",
            description: "Design and deploy a zero-trust network model for an enterprise, covering identity verification, micro-segmentation, and least-privilege access.",
            skills: ["Cloud Computing", "Cybersecurity", "Python"],
            popularity: 5,
            capacity: 2,
            status: "active",
            type: "teacher",
            category: "Security",
            major: "CCS",
            createdAt: "2025-02-05"
        },
        {
            id: 13,
            title: "Phishing Email Detection using Deep Learning",
            supervisor: "Prof. Bell Liu",
            supervisorId: "T001",
            supervisorEmail: "t001@hkmu.edu.hk",
            description: "Train a deep neural network to classify emails as phishing or legitimate, with explainability features highlighting suspicious elements.",
            skills: ["Python", "Deep Learning", "Cybersecurity"],
            popularity: 11,
            capacity: 2,
            status: "active",
            type: "teacher",
            category: "AI/ML",
            major: "CCS",
            createdAt: "2025-02-08"
        },
        {
            id: 14,
            title: "Privacy-Preserving Data Aggregation System",
            supervisor: "Prof. Alex Foster",
            supervisorId: "T002",
            supervisorEmail: "t002@hkmu.edu.hk",
            description: "Implement privacy-preserving aggregation techniques (e.g., differential privacy, secure multi-party computation) for sensitive datasets.",
            skills: ["Python", "Machine Learning", "Blockchain"],
            popularity: 6,
            capacity: 2,
            status: "active",
            type: "teacher",
            category: "Security",
            major: "CCS",
            createdAt: "2025-02-10"
        },
        {
            id: 15,
            title: "Security Operations Center Dashboard",
            supervisor: "Prof. Priya Sharma",
            supervisorId: "T006",
            supervisorEmail: "t006@hkmu.edu.hk",
            description: "Build a real-time SOC dashboard integrating SIEM data, alerting rules, and incident ticketing for security analysts.",
            skills: ["Web Development", "Cybersecurity", "JavaScript"],
            popularity: 8,
            capacity: 3,
            status: "active",
            type: "teacher",
            category: "Security",
            major: "CCS",
            createdAt: "2025-02-12"
        },

        // ── ECE Projects (projects 16-30, major = ECE) ──────────────────────
        {
            id: 16,
            title: "IoT-based Environmental Monitoring System",
            supervisor: "Prof. James Lee",
            supervisorId: "T007",
            supervisorEmail: "t007@hkmu.edu.hk",
            description: "Deploy a sensor network to monitor air quality, temperature, and humidity across campus, with a real-time web dashboard.",
            skills: ["IoT", "Embedded Systems", "Python"],
            popularity: 14,
            capacity: 3,
            status: "active",
            type: "teacher",
            category: "IoT",
            major: "ECE",
            createdAt: "2025-01-16"
        },
        {
            id: 17,
            title: "Smart Campus Energy Management System",
            supervisor: "Prof. Carlos Rivera",
            supervisorId: "T009",
            supervisorEmail: "t009@hkmu.edu.hk",
            description: "Design an IoT-driven energy management platform to monitor and optimize electricity usage across campus buildings.",
            skills: ["IoT", "Data Science", "Python"],
            popularity: 10,
            capacity: 2,
            status: "active",
            type: "teacher",
            category: "IoT",
            major: "ECE",
            createdAt: "2025-01-11"
        },
        {
            id: 18,
            title: "Autonomous Delivery Robot",
            supervisor: "Prof. Mei Zhang",
            supervisorId: "T008",
            supervisorEmail: "t008@hkmu.edu.hk",
            description: "Develop a small indoor autonomous robot capable of delivering items on campus using SLAM-based navigation.",
            skills: ["IoT", "Embedded Systems", "Python"],
            popularity: 12,
            capacity: 3,
            status: "active",
            type: "teacher",
            category: "Robotics",
            major: "ECE",
            createdAt: "2025-01-14"
        },
        {
            id: 19,
            title: "Smart Home Automation System",
            supervisor: "Prof. Aisha Mohammed",
            supervisorId: "T010",
            supervisorEmail: "t010@hkmu.edu.hk",
            description: "Build a smart home hub integrating lighting, climate control, and security cameras with voice control and mobile app support.",
            skills: ["IoT", "Mobile Development", "Embedded Systems"],
            popularity: 13,
            capacity: 3,
            status: "active",
            type: "teacher",
            category: "IoT",
            major: "ECE",
            createdAt: "2025-01-09"
        },
        {
            id: 20,
            title: "5G Network Coverage Optimization",
            supervisor: "Prof. Ryan Park",
            supervisorId: "T011",
            supervisorEmail: "t011@hkmu.edu.hk",
            description: "Simulate and optimize 5G small-cell placement for campus-wide coverage using ray-tracing and machine learning prediction.",
            skills: ["IoT", "Machine Learning", "Python"],
            popularity: 8,
            capacity: 2,
            status: "active",
            type: "teacher",
            category: "Wireless",
            major: "ECE",
            createdAt: "2025-01-06"
        },
        {
            id: 21,
            title: "Industrial IoT Predictive Maintenance Platform",
            supervisor: "Prof. James Lee",
            supervisorId: "T007",
            supervisorEmail: "t007@hkmu.edu.hk",
            description: "Create a platform that collects vibration and temperature data from industrial machinery to predict failures before they occur.",
            skills: ["IoT", "Machine Learning", "Python"],
            popularity: 9,
            capacity: 2,
            status: "active",
            type: "teacher",
            category: "IoT",
            major: "ECE",
            createdAt: "2025-01-19"
        },
        {
            id: 22,
            title: "Real-time Signal Processing for Audio Applications",
            supervisor: "Prof. Mei Zhang",
            supervisorId: "T008",
            supervisorEmail: "t008@hkmu.edu.hk",
            description: "Implement real-time DSP algorithms (filtering, FFT, noise cancellation) on embedded hardware for audio enhancement.",
            skills: ["IoT", "Embedded Systems", "C/C++"],
            popularity: 7,
            capacity: 2,
            status: "active",
            type: "teacher",
            category: "Signal Processing",
            major: "ECE",
            createdAt: "2025-01-21"
        },
        {
            id: 23,
            title: "Smart Grid Load Balancing System",
            supervisor: "Prof. Carlos Rivera",
            supervisorId: "T009",
            supervisorEmail: "t009@hkmu.edu.hk",
            description: "Design an optimization algorithm for balancing loads across a simulated microgrid, with demand-response integration.",
            skills: ["IoT", "Machine Learning", "Python"],
            popularity: 6,
            capacity: 2,
            status: "active",
            type: "teacher",
            category: "Power Systems",
            major: "ECE",
            createdAt: "2025-01-23"
        },
        {
            id: 24,
            title: "Wearable Health Monitoring Device",
            supervisor: "Prof. Aisha Mohammed",
            supervisorId: "T010",
            supervisorEmail: "t010@hkmu.edu.hk",
            description: "Develop a wearable device that tracks heart rate, SpO2, and temperature, transmitting data to a cloud dashboard in real time.",
            skills: ["IoT", "Embedded Systems", "Mobile Development"],
            popularity: 11,
            capacity: 3,
            status: "active",
            type: "teacher",
            category: "Healthcare",
            major: "ECE",
            createdAt: "2025-01-26"
        },
        {
            id: 25,
            title: "FPGA-based Real-time Image Processing",
            supervisor: "Prof. Ryan Park",
            supervisorId: "T011",
            supervisorEmail: "t011@hkmu.edu.hk",
            description: "Implement real-time image processing kernels (edge detection, feature extraction) on an FPGA development board.",
            skills: ["IoT", "Embedded Systems", "C/C++"],
            popularity: 5,
            capacity: 2,
            status: "active",
            type: "teacher",
            category: "Signal Processing",
            major: "ECE",
            createdAt: "2025-01-29"
        },
        {
            id: 26,
            title: "Autonomous Navigation System for Drones",
            supervisor: "Prof. James Lee",
            supervisorId: "T007",
            supervisorEmail: "t007@hkmu.edu.hk",
            description: "Develop a flight controller and navigation algorithm for a small quadcopter, including obstacle avoidance using computer vision.",
            skills: ["IoT", "Machine Learning", "Python"],
            popularity: 10,
            capacity: 3,
            status: "active",
            type: "teacher",
            category: "Robotics",
            major: "ECE",
            createdAt: "2025-02-02"
        },
        {
            id: 27,
            title: "Wireless Sensor Network for Agriculture",
            supervisor: "Prof. Mei Zhang",
            supervisorId: "T008",
            supervisorEmail: "t008@hkmu.edu.hk",
            description: "Deploy a low-power WSN in a greenhouse to monitor soil moisture, light, and temperature, with automated irrigation control.",
            skills: ["IoT", "Embedded Systems", "Python"],
            popularity: 8,
            capacity: 2,
            status: "active",
            type: "teacher",
            category: "IoT",
            major: "ECE",
            createdAt: "2025-02-04"
        },
        {
            id: 28,
            title: "Mixed-Signal IC Design for IoT Applications",
            supervisor: "Prof. Carlos Rivera",
            supervisorId: "T009",
            supervisorEmail: "t009@hkmu.edu.hk",
            description: "Design and layout a mixed-signal IC integrating an analog front-end and digital signal processing core for IoT sensing.",
            skills: ["IoT", "Embedded Systems", "C/C++"],
            popularity: 4,
            capacity: 2,
            status: "active",
            type: "teacher",
            category: "IC Design",
            major: "ECE",
            createdAt: "2025-02-06"
        },
        {
            id: 29,
            title: "Vehicle-to-Vehicle Communication System",
            supervisor: "Prof. Aisha Mohammed",
            supervisorId: "T010",
            supervisorEmail: "t010@hkmu.edu.hk",
            description: "Simulate a V2V communication protocol for collision avoidance, including message authentication and latency analysis.",
            skills: ["IoT", "Machine Learning", "Python"],
            popularity: 7,
            capacity: 2,
            status: "active",
            type: "teacher",
            category: "Wireless",
            major: "ECE",
            createdAt: "2025-02-09"
        },
        {
            id: 30,
            title: "Smart Parking Management System",
            supervisor: "Prof. Ryan Park",
            supervisorId: "T011",
            supervisorEmail: "t011@hkmu.edu.hk",
            description: "Build an IoT-enabled parking system with ultrasonic/IR sensors, a mobile app for spot availability, and automatic fee calculation.",
            skills: ["IoT", "Mobile Development", "Python"],
            popularity: 9,
            capacity: 3,
            status: "active",
            type: "teacher",
            category: "IoT",
            major: "ECE",
            createdAt: "2025-02-11"
        },

        // ── Student-proposed project (hidden from teacher All Projects list) ──
        {
            id: 101,
            title: "Student Research Project 1",
            description: "A student-proposed project",
            skills: ["Research"],
            popularity: 0,
            capacity: 1,
            status: "active",
            type: "student",
            proposalStatus: "pending",
            proposedBy: "S001",
            createdAt: "2025-02-01"
        }
    ],

    students: [
        {
            id: "s001",
            name: "Chan Tai Man",
            email: "s001@hkmu.edu.hk",
            gpa: "3.45",
            major: "Computer and Cyber Security",
            year: "Year 4",
            preferences: [],
            proposalSubmitted: false,
            assignedProject: null
        }
    ],

    preferences: [],

    assignments: [],

    system: {
        currentPhase: "preference",
        deadlines: {
            studentSelfProposal: "2025-03-20T23:59:00",
            preference: "2025-04-15T22:59:00",
            teacherProposalReview: "2025-04-15T23:59:00",
            teacherSelfProposal: "2025-05-30T23:59:00"
        },
        matchingCompleted: false
    }
};

const { applySupervisorsToMockProjects } = require('./projectCatalogSync');
mockData.projects = applySupervisorsToMockProjects(mockData.projects);

module.exports = mockData;
